# Generated by Django 3.2.6 on 2022-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_bookpdf_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpdf',
            name='external_file_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
