# Generated by Django 3.2.6 on 2022-04-06 06:59

import apps.home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_quranchapterold'),
    ]

    operations = [
        migrations.CreateModel(
            name='HadithBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HadithBookMainChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(max_length=3)),
                ('english_name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(max_length=200)),
                ('hadithbook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hadithbook')),
            ],
        ),
        migrations.AlterField(
            model_name='bookpdf',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to=apps.home.models.BookPDF_upload_location),
        ),
        migrations.CreateModel(
            name='HadithBookSubChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_chapter_name', models.CharField(max_length=200)),
                ('hadith_book_main_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hadithbookmainchapter')),
            ],
        ),
        migrations.CreateModel(
            name='HadithBookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arabic_content', models.TextField()),
                ('roman_urdu_content', models.TextField()),
                ('hindi_content', models.TextField()),
                ('reference_field', models.TextField()),
                ('grade', models.CharField(choices=[("Muttafaqun 'alayh", "Muttafaqun 'alayh"), ('Sahih', 'Sahih'), ('Hasan', 'Hasan'), ('Zaeef', 'Zaeef')], default='Sahih', max_length=50)),
                ('hadith_book_sub_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hadithbooksubchapter')),
            ],
        ),
    ]
