# Generated by Django 3.2.6 on 2022-04-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220406_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadithbookcontent',
            name='sr_no',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
