# Generated by Django 3.2.6 on 2022-04-09 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_hadithbookcontent_sr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadithbook',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
