# Generated by Django 3.2.6 on 2022-04-12 09:22

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hadithbookexcelfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadithbookexcelfile',
            name='HadithBookMainChapter',
        ),
        migrations.RemoveField(
            model_name='hadithbookexcelfile',
            name='HadithBookSubChapter',
        ),
        migrations.AddField(
            model_name='hadithbookexcelfile',
            name='hadith_book_main_chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Hadithbook', chained_model_field='hadithbook', default=1, on_delete=django.db.models.deletion.CASCADE, to='home.hadithbookmainchapter'),
            preserve_default=False,
        ),
    ]
