# Generated by Django 3.2.6 on 2022-04-12 09:34

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220412_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='hadithbookexcelfile',
            name='Hadith_book_sub_chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hadith_book_main_chapter_excel', chained_model_field='hadith_book_main_chapter', default=1, on_delete=django.db.models.deletion.CASCADE, to='home.hadithbookmainchapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hadithbookexcelfile',
            name='hadith_book_main_chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Hadithbook', chained_model_field='hadithbook', on_delete=django.db.models.deletion.CASCADE, related_name='hadith_book_main_chapter_excel', to='home.hadithbookmainchapter'),
        ),
    ]
