# Generated by Django 3.2.6 on 2022-04-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20220412_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadithbookexcelfile',
            name='Hadithbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Hadithbook_excel', to='home.hadithbook'),
        ),
    ]
