# Generated by Django 3.2.6 on 2022-04-13 00:56

import apps.home.models
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_hadithbookexcelfile_hadithbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadithbookcontent',
            name='arabic_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadithbookcontent',
            name='grade',
            field=models.CharField(blank=True, choices=[("Muttafaqun 'alayh", "Muttafaqun 'alayh"), ('Sahih', 'Sahih'), ('Hasan', 'Hasan'), ('Zaeef', 'Zaeef')], default='Sahih', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hadithbookcontent',
            name='hindi_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadithbookcontent',
            name='reference_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadithbookcontent',
            name='roman_urdu_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hadithbookcontent',
            name='sr_no',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='hadithbookexcelfile',
            name='Hadith_book_sub_chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hadith_book_main_chapter', chained_model_field='hadith_book_main_chapter', on_delete=django.db.models.deletion.CASCADE, to='home.hadithbooksubchapter'),
        ),
        migrations.AlterField(
            model_name='hadithbookexcelfile',
            name='file_url',
            field=models.FileField(upload_to=apps.home.models.hadith_excel_upload_location),
        ),
    ]
