# Generated by Django 3.2.6 on 2022-04-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220413_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('quran', 'quran'), ('hadith', 'hadith'), ('dua', 'dua')], default='hadith', max_length=100),
        ),
    ]
